# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nico Boyce
tagline:          'Person doing human things'
description:      'Person doing human things'
url:              https://nicoboyce.com
baseurl:          /
email:            hello@nicoboyce.com

author:
  name:           'Nico Boyce'
  url:            https://nicoboyce.com

# paginate:         4

# plugins:
#  - jekyll-paginate-v2
#  - jekyll-gist

# Custom vars
version:          24.05

excerpt_separator: "<!--excerpt-end-->"
# github:
#   repo:           https://github.com/poole/hyde
