# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nico Boyce
tagline:          'Person doing human things'
description:      'Person doing human things'
url:              https://nicoboyce.com
baseurl:          /
email:            hello@nicoboyce.com

author:
  name:           'Nico Beastie Boyce'
  url:            https://nicoboyce.com


excerpt_separator: "<!--excerpt-end-->"
okay:             idk-lol
# github:
#   repo:           https://github.com/poole/hyde